### PR TITLE
docs: add office hour 03112023

### PR DESCRIPTION
**Pull request by tomaszbarwicki**
PR to add 03/11/2023 Office Hours meeting minutes to the Catena-X blog.

Fixes https://github.com/eclipse-tractusx/sig-infra/issues/337

### CODE REVIEW

**Review by almadigabor — APPROVED** [review]
@tomaszbarwicki  Text looks good, but there are some lint errors that needs to be fixed.

**Review by FaGru3n — APPROVED** [review]
LGTM

**Comment by tomaszbarwicki** [comment]
> @tomaszbarwicki Text looks good, but there are some lint errors that needs to be fixed.

@almadigabor can you provide example of the lint errors I need to fix?

**Review by FaGru3n — APPROVED** [review]
LGTM

**Pull request merged**
