### PR TITLE
Chore/a1 odt 484 vault config

### PR DESCRIPTION
**Pull request by csaba-fabian**
Describe how to deploy and configure Hashicorp Vault

### CODE REVIEW

**Review by carslen — CHANGES_REQUESTED** [review]
To fix currently broken markdown linting please edit `package.json` file and change line 15 from

```
    "lint": "markdownlint --ignore node_modules --config .markdownlint.json '**/*.md'",
```
to
```
    "lint": "markdownlint --ignore node_modules --config .markdownlint.json **/*.md",
```
Then run `npm run lint` locally and fix linting errors. Please do not commit the changed `package.json` until we've determined a valid fix for this issue.

Some additional remarks:
- please avoid link collections (the start of this file looks like one), use `[link description](URI)` instead.
- I'm unhappy to expose Azure tenant ID`s in documentations which is public to the internet.

**Comment by carslen** [comment]
Unfortunately you've also to fix the linting errors in file `SECRETS.md` to be able to commit after removing the quotes in `package.json`.

**Comment by csaba-fabian** [comment]
after I removed the quotation marks and ran the `npm run lint` command, only got this as an output:
> catenax-ng@0.0.0 lint
> markdownlint --ignore node_modules --config .markdownlint.json **/*.md

**Comment by carslen** [comment]
Still unhappy with the links in the first section :) And also with these extra long headings.

Please put this into a code block:
image

**Comment by carslen** [comment]
Linting itself is OK now. :)

**Comment by csaba-fabian** [comment]
do you mean to remove the links altogether?
should I move all instructions inline with the code?

**Review by ricogu — APPROVED** [review]

**Review by ricogu — APPROVED** [review]

**Pull request merged**
